#!/usr/bin/env bash
#This script prings a message, saves its PID, and handkes signals

echo $$ > /tmp/myscript.pid

trap 'echo "Y U no love me?!"; rm -f /tmp/myscript.pid; exit' SIGINT
trap 'echo "I hate the kill command"; rm -f /tmp/myscript.pid; exit' SIGTERM
trap 'rm -f /tmp/myscript.pid; exit' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 1
done
